name: Security Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  security-tests:
    uses: tjaung/cs6620_project/.github/workflows/securitytests.yaml@tj/connect-all
    permissions:
      id-token: write
      contents: read
    with:
      scanners: sast,pentest
      app_port: "3000"
      app_health_path: /health
      pentest_target_paths: /api/v1/pentest/status,/api/v1/pentest/scan
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}