name: Security Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  security-tests:
    uses: tjaung/cs6620_project/.github/workflows/securitytests.yaml@tj/connect-all
    permissions:
      id-token: write
      contents: read
    with:
      scanners: sast,pentest
      pentest_target_url: http://example.com/api/users
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
